### ISSUE TITLE
Improve UI folder dropdown list

### ISSUE THREAD

**Issue by SarwinR** [SarwinR/better-classroom#14]
Improve the UI design of the folder dropdown list, making it more user friendly.

Current Dropdown List:
![image](https://user-images.githubusercontent.com/64829298/236680865-71c8c2ce-cc07-4465-9727-49bb8ff264d3.png)

**Comment by anxbt** [comment]
in order to do this,which folder should i make changes to.Pls help me as tis is my 1st open source contribution

**Comment by SarwinR** [comment]
Hi @anxbt, the files that you most likely will have to modify are:
- html/dropdown_list.html
- css/style.css

I hope this helps you get started with your first open-source contribution! Good luck and have fun coding!
