### ISSUE TITLE
Add extension version in popup

### ISSUE THREAD

**Issue by SarwinR** [SarwinR/better-classroom#19]
Add the extension's version number to the extension popup (popup.html)

Current Popup:
![image](https://user-images.githubusercontent.com/64829298/236789120-71b99383-1eb2-4751-a30e-315a7d426a47.png)

**Comment by anxbt** [comment]
Extension's version number added
![Screenshot 2023-05-08 173202](https://user-images.githubusercontent.com/127748618/236819302-626f1d8a-1b30-41f8-b0d5-86e52cef9ab8.png)

**Comment by SarwinR** [comment]
Please create a pull request so that I can check if it works.

**Comment by anxbt** [comment]
i have already  commited to the main branch on "anxbrt" can you please check tht out

**Comment by SarwinR** [comment]
Hi, you will have to create a pull request. Here are some resources on how to do that:
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
- https://opensource.com/article/19/7/create-pull-request-github
