### ISSUE TITLE
Classroom folders are removed when going to a different computer

### ISSUE THREAD

**Issue by aglasgow-nhs** [SarwinR/better-classroom#27]
Hi there, 

First of all, thank you! This plugin is near perfect and I've been suggesting to Google for years that they need to have this facility for google classroom folders. 

I sent it my colleagues today and one of them quite rightly pointed out that once you setup your folders on one computer, and then go to another computer, the folders aren't there. Does this therefore mean that the classes are stored locally? Is there anything we can do to ensure that the classes roam with us from computer to computer throughout the school? 

I personally have over 100 classes which I oversee so this is a super useful extension. 

Thank you in advance. 

Alan

**Comment by SarwinR** [comment]
Hi Alan,

Thanks for your feedback and for sharing the plugin! Currently, folder information is stored locally, so it doesn't transfer between computers. I’m working on a way to export and import folders so that you can easily transfer them between computers.

You can track the progress of the feature here: #28 

Thanks for your patience!
@SarwinR

**Comment by SarwinR** [comment]
Hi Alan, 

The extension has been updated with the requested feature.
Check out the update:
<a href="https://microsoftedge.microsoft.com/addons/detail/ofjjjjceeenagpnglijjmhbjlgidhiml" target="_blank"><img src="https://img.shields.io/badge/Edge%20Add%20Ons-v1.1.4.1-g.svg"/></a> <a target="_blank" href="https://chrome.google.com/webstore/detail/better-classroom/maibneeahfkanhakkogkbcakcadjejkl"><img src="https://img.shields.io/badge/Chrome%20Web%20Store-v1.1.4-g.svg"/></a>

![image](https://github.com/SarwinR/better-classroom/assets/64829298/8ac662e9-1221-4d13-81d3-fad601514b41)

Thank you for your patience!
@SarwinR
