### ISSUE TITLE
Modal Close button onHover Design Not as Intended

### ISSUE THREAD

**Issue by SarwinR** [SarwinR/better-classroom#7]
When hovering over the close button in modals such as the Folder Creation Modal or Folder Settings Modal, the background appears to be an oval shape instead of a circle.

![image](https://user-images.githubusercontent.com/64829298/234559520-9192b5e2-f140-402b-a325-57a18cd00ec8.png)

**Comment by GFerreiroS** [comment]
Can i get assigned? I already made it work.

**Comment by SarwinR** [comment]
> Can i get assigned? I already made it work.

sure

**Comment by GFerreiroS** [comment]
I've opened a pull request, feel free to give feedback.
